### ISSUE TITLE
"in" sometimes recognised as function call by syntax highlighting

### ISSUE THREAD

**Issue by Sainan** [PlutoLang/plutolang.github.io#23]
https://pluto-lang.org/docs/New%20Features/In%20Expressions

![image](https://github.com/PlutoLang/plutolang.github.io/assets/63328889/deb888d3-a7e6-4d9b-b488-095cfba08c98)

**Comment by well-in-that-case** [comment]
Fixed in 76ee6037642bd45c5e1b7b0d8e82eecf0311ec4a
